# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8088
#    context-path: /dbAdmin

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/admin?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
    #为解决thymeleaf 需要结束标签添加
    mode: LEGACYHTML5
  mvc:
    static-path-pattern: /static/**
  redis:
      database: 1
      host: 127.0.0.1
      port: 6379
      password:       # 密码（默认为空）
      timeout: 6s  # 连接超时时长（毫秒）
      jedis:
              pool:
                #最大连接数
                max-active: 8
                #最大阻塞等待时间(负数表示没限制)
                max-wait: -1ms
                #最大空闲
                max-idle: 8
                #最小空闲
                min-idle: 0


#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: org.db.admin.entity
  #  typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    #refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    #sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#日志
logging:
  level: info

#自定义
custom:
  redis:
      # 是否开启redis缓存  true开启   false关闭
      open: false
  shiro:
      # true表示shiro session存到redis里，需要开启redis，才会生效【分布式场景】
      redis: false